"""HTML 리포트 생성."""

import json
import sys
import os
from datetime import datetime

from analyzer import analyze_watchlist
from gem_scanner import scan_gems


SIGNAL_KR = {
    "strong_buy": "강력 매수",
    "buy": "매수",
    "hold": "보유",
    "sell": "매도",
    "strong_sell": "강력 매도",
    "bullish": "강세",
    "bearish": "약세",
    "neutral": "중립",
    "overbought": "과매수",
    "oversold": "과매도",
    "normal": "정상",
    "uptrend": "상승",
    "downtrend": "하락",
    "sideways": "횡보",
}

REC_COLOR = {
    "strong_buy": "#00C853",
    "buy": "#4CAF50",
    "hold": "#FF9800",
    "sell": "#F44336",
    "strong_sell": "#B71C1C",
}


def format_price(price, currency):
    if currency == "KRW":
        return f"₩{price:,.0f}"
    elif currency == "HKD":
        return f"HK${price:,.2f}"
    elif currency == "CNY":
        return f"¥{price:,.2f}"
    return f"${price:,.2f}"


def format_change(change_pct):
    if change_pct > 0:
        return f'<span style="color:#F44336">+{change_pct:.2f}%</span>'
    elif change_pct < 0:
        return f'<span style="color:#2196F3">{change_pct:.2f}%</span>'
    return f'{change_pct:.2f}%'


def generate_html(watchlist_path):
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # 관심종목 분석
    print("=== Watchlist Analysis ===", file=sys.stderr)
    results = analyze_watchlist(watchlist_path)

    krx_stocks = [r for r in results if r['market'] == 'KRX']
    us_stocks = [r for r in results if r['market'] == 'US']

    # 숨겨진 종목 스캔
    print("=== Gem Scanner ===", file=sys.stderr)
    gems = scan_gems(top_n=10)

    # HTML 생성
    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f5f5f5; padding: 20px; color: #333; }}
  .container {{ max-width: 800px; margin: 0 auto; }}
  h1 {{ color: #1a1a2e; border-bottom: 3px solid #16213e; padding-bottom: 10px; }}
  h2 {{ color: #16213e; margin-top: 30px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 15px 0; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
  th {{ background: #16213e; color: white; padding: 12px 10px; text-align: left; font-size: 13px; }}
  td {{ padding: 10px; border-bottom: 1px solid #eee; font-size: 13px; }}
  tr:hover {{ background: #f8f9fa; }}
  .rec {{ padding: 3px 8px; border-radius: 4px; color: white; font-weight: bold; font-size: 12px; }}
  .gem-card {{ background: white; padding: 12px 16px; margin: 8px 0; border-radius: 8px; border-left: 4px solid #FF9800; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
  .gem-name {{ font-weight: bold; font-size: 15px; }}
  .gem-reason {{ color: #e65100; font-size: 13px; margin-top: 4px; }}
  .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px; }}
  .section-note {{ color: #666; font-size: 13px; margin-bottom: 10px; }}
</style>
</head>
<body>
<div class="container">
<h1>Daily Stock Report</h1>
<p style="color:#666">{now} KST</p>
"""

    # 한국 주식 테이블
    if krx_stocks:
        html += _build_stock_table("한국 주식 (KRX)", krx_stocks)

    # 미국 주식 테이블
    if us_stocks:
        html += _build_stock_table("미국 주식 (US)", us_stocks)

    # 숨겨진 종목 추천
    html += '<h2>숨겨진 종목 추천</h2>'
    html += '<p class="section-note">KOSPI/KOSDAQ 중 거래량 급증 또는 RSI 과매도 종목</p>'

    if gems:
        for g in gems:
            color = "#4CAF50" if g['change_pct'] >= 0 else "#2196F3"
            html += f"""<div class="gem-card">
  <span class="gem-name">{g['name']}</span> <span style="color:#999">({g['ticker']})</span>
  <span style="margin-left:10px">₩{g['price']:,.0f}</span>
  <span style="color:{color}; margin-left:5px">{g['change_pct']:+.2f}%</span>
  <div class="gem-reason">{g['reason']}</div>
</div>"""
    else:
        html += '<p style="color:#999">오늘은 조건에 부합하는 종목이 없습니다.</p>'

    html += """
<div class="footer">
  <p>이 리포트는 과거 데이터 기반 기술적 분석이며, 투자 판단의 최종 책임은 본인에게 있습니다.</p>
  <p>Data source: Yahoo Finance (yfinance) | Generated by daily-stock-report</p>
</div>
</div>
</body>
</html>"""

    return html


def _build_stock_table(title, stocks):
    html = f'<h2>{title}</h2>'
    html += """<table>
<tr>
  <th>종목</th><th>현재가</th><th>등락률</th>
  <th>RSI</th><th>MACD</th><th>추세</th><th>추천</th>
</tr>"""

    for s in stocks:
        sig = s['signals']
        rec = sig['recommendation']
        rec_kr = SIGNAL_KR.get(rec, rec)
        rec_color = REC_COLOR.get(rec, "#999")
        trend_kr = SIGNAL_KR.get(sig['trend'], sig['trend'])
        macd_kr = SIGNAL_KR.get(sig['macd_signal'], sig['macd_signal'])

        rsi_color = ""
        if s['rsi_14'] and s['rsi_14'] > 70:
            rsi_color = 'color:#F44336'
        elif s['rsi_14'] and s['rsi_14'] < 30:
            rsi_color = 'color:#2196F3'

        html += f"""<tr>
  <td><strong>{s['name']}</strong><br><span style="color:#999;font-size:11px">{s['ticker']}</span></td>
  <td>{format_price(s['price'], s['currency'])}</td>
  <td>{format_change(s['change_pct'])}</td>
  <td style="{rsi_color}">{s['rsi_14'] or '-'}</td>
  <td>{macd_kr}</td>
  <td>{trend_kr}</td>
  <td><span class="rec" style="background:{rec_color}">{rec_kr}</span></td>
</tr>"""

    html += "</table>"
    return html


if __name__ == "__main__":
    watchlist_path = sys.argv[1] if len(sys.argv) > 1 else "watchlist.json"
    html = generate_html(watchlist_path)
    print(html)
